apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: site
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: site
    spec:
      volumes:
      - name: html
        configMap:
          name: html
          items:
            - key: index.html
              path: index.html
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: html
status: {}
